management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
  server:
    port: 8090

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 5
        failureRateThreshold: 90
        waitDurationInOpenState: 5s
        automaticTransitionFromOpenToHalfOpenEnabled: true
        permittedNumberOfCallsInHalfOpenState: 3
        slowCallRateThreshold: 80
        slowCallDurationThreshold: 300ms
        writableStackTraceEnabled: false
    instances:
      testService:
        baseConfig: default
        waitDurationInOpenState: 15s
        slowCallDurationThreshold: 1000ms

  bulkhead:
    configs:
      default:
        maxConcurrentCalls: 5
        maxWaitDuration: 0ms
        writableStackTraceEnabled: false
      instances:
        testService:
          baseConfig: default
